import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class GuessTheNumberGame extends JFrame implements ActionListener {
  private static final int MAX_GUESSES = 10; // Maximum number of guesses allowed
  private static final int MAX_NUMBER = 100; // Maximum number that can be generated
  private int randomNumber; // The random number generated by the computer
  private int numGuesses; // The number of guesses made by the player
  private JLabel promptLabel;
  private JTextField guessTextField;
  private JButton guessButton;
  private JLabel resultLabel;

  public GuessTheNumberGame() {
    // Initialize the game
    randomNumber = (int) (Math.random() * MAX_NUMBER) + 1;
    numGuesses = 0;

    // Create the GUI components
    promptLabel = new JLabel("Guess a number between 1 and " + MAX_NUMBER);
    guessTextField = new JTextField(10);
    guessButton = new JButton(" Guess");
    guessButton.addActionListener(this);
    resultLabel = new JLabel();

    // Add the components to the frame
    JPanel panel = new JPanel();
    panel.setLayout(new GridLayout(3, 2));
    panel.add(promptLabel);
    panel.add(guessTextField);
    panel.add(guessButton);
    panel.add(resultLabel);
    getContentPane().add(panel);

    // Set the frame properties
    setTitle("Guess The Number Game");
    setSize(400, 200);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setVisible(true);
  }

  public void actionPerformed(ActionEvent e) {
    // Handle the button click
    if (e.getSource() == guessButton) {
      int guess = Integer.parseInt(guessTextField.getText());
      numGuesses++;

      if (guess == randomNumber) {
        resultLabel.setText("You guessed the number in " + numGuesses + " attempts! You Win the Match");
        guessButton.setEnabled(false);
      } else if (numGuesses == MAX_GUESSES) {
        resultLabel.setText("Sorry, you have used up all " + MAX_GUESSES + " attempts. The number was " + randomNumber + ".");
        guessButton.setEnabled(false);
      } else if (guess < randomNumber) {
        resultLabel.setText("Too low. Try again.");
      } else {
        resultLabel.setText("Too high. Try again.");
      }
    }
  }

  public static void main(String[] args) {
    new GuessTheNumberGame();
  }
}
